### ISSUE TITLE
The future of cgmath

### ISSUE THREAD

**Issue by bjz** [bjz/cgmath-rs#144]
I currently am stretching myself quite thin when it comes to projects, and I feel like I am no longer able to adequately steer the development of cgmath going forwards. I am also considering moving to @sebcrozet's [nalgebra](https://github.com/sebcrozet/nalgebra) library for my future projects. I can continue to merge PRs, but I can't see myself contributing much heading into the future. If somebody has the passion or energy to spare to keep things going, I am also happy to transfer ownership of the repository.

**Comment by kvark** [comment]
This is very sad to hear!

Looking at `nalgebra`, I don't see anything similar to our `Transform` trait and `Decomposed` implementation. Thus, I'm gonna continue using cgmath for the nearest future.

**Comment by kvark** [comment]
See also: discussion about the differences between cgmath and nalgebra: https://github.com/sebcrozet/nalgebra/issues/23

**Comment by jarrett** [comment]
Having tried cgmath, nalgebra, and vecmath, I committed to cgmath for my projects. I'd be interested in assisting with the future of this library, whether that means it continues independently or merges with another library.

I'd also be interested in expanding the functionality of cgmath or its successor library. On top of cgmath, I've implemented some features that should be useful to other game developers, including intersections between lines and 3D AABBs:

https://github.com/jarrett/cities/tree/master/src/math

**Comment by kvark** [comment]
@jarrett Have you see the [Bound](https://github.com/bjz/cgmath-rs/blob/master/src/bound.rs#L35) trait? Perhaps, you could integrate part of your code by implementing `Bound::relate_ray()` and `Bound::relate_bound` for existing bounds.

**Comment by jarrett** [comment]
Just to clarify, are you saying the `Bound` trait would gain `relate_ray` and `relate_bound` as required or provided methods?

**Comment by kvark** [comment]
@jarrett I meant add `relate_ray()` and `relate_bound()` to the `Bound` trait and implement them for particular types (points, spheres, boxes, etc).

**Comment by jarrett** [comment]
Ok. So they'd be required methods, not provided methods. Correct? If so, then I think that should work.

**Comment by kvark** [comment]
@jarrett yep, I don't think you can derive one from another.

**Comment by jarrett** [comment]
Three issues:

First issue: My implementation depends on the line being [represented in parametric form](https://github.com/jarrett/cities/blob/5be4ab80d8db7586e715e82b7494c0fd13da9a8d/src/math/line.rs#L4).  Whereas cgmath's `Line3` has a different representation. I'm guessing you don't want to add my custom `PLine3` type to cgmath. So one option is to add fields to the `Line3` struct for `dx`, `dy`, and `dz` at the cost of extra memory. Another option is to add `dx()`, `dy()`, and `dz()` methods to `Line3` at the cost of CPU cycles every time those values are used.

Second issue: Would it have to be `relate_bound3` instead of `relate_bound`? Or is there a way to make that generic? Sorry, I'm still not clear on the big picture you have in mind for the `Bound` trait.

Third issue: Suppose I have time in the near future to implement `relate_bound3` for `Line3`, but not for spheres etc. Should I just implement `relate_bound3` on the other types with a panic? E.g.:

    impl<S: BaseFloat + 'static> Bound<S> for Sphere<S> {
        // ...
    
        fn relate_bound3(&self, bb: &Aabb3<S>) -> {
            panic!("Not implemented.");
        }
    }

By the way: Before I go farther down this rabbit hole, where do we stand on the future of this library? Does it make sense to continue expanding its features? Or will it be merged with another library?

**Comment by kvark** [comment]
@jarrett 

1. There is no line in `cgmath` anyway, it's the `Ray`, which goes only one direction. What do you need lines for?

2. `fn relate_bound(&self, other: &Self) -> Relation`. Strictly speaking, all currently implemented bounds are 3D, and this would be nice to extend to N dimensions, maybe at some point...

3. You can't implement `Bound` for your `Line3`, because it doesn't make for a line to be a bound to anything. Bounds are:
  - `Point3` (trivial case)
  - `Sphere`
  - `Aabb3`
  - `Obb`

> Before I go farther down this rabbit hole, where do we stand on the future of this library? Does it make sense to continue expanding its features? Or will it be merged with another library?

I can't answer for everyone. I don't hear too many strong opinions on the matter (unfortunately). But I'm continuing using it and extending it (all the `Bound` stuff was added after this issue) for [gfx_scene](https://github.com/kvark/gfx_scene), [claymore](https://github.com/kvark/claymore), and other projects. I can see certain interest from @csherratt as well. We have the access and can develop the library without @bjz participation. I'm not aware of any plans to merge it with nalgebra or anything, outside of vague wishes.

**Comment by jarrett** [comment]
1. p`Line` does exist](https://github.com/bjz/cgmath-rs/blob/182f7b41dcdff2b21fbeacd6f3329d98ea72f462/src/line.rs). One good use is to represent the mouse position with an orthographic projection. (The way I typically model ortho, the camera has no position. Thus the mouse position describes a line rather than a ray.)

2. I guess I don't understand how you envision the `Bound` trait fitting together. I.e. which types have the trait implemented, and which types can be passed as the parameter to `relate_bound`. When I get a chance, I'll take a look at your existing code and see if I can infer as much.

**Comment by kvark** [comment]
@jarrett yes, my bad, line truly exists ;) We can have a default implementation for `relate_line` by calling `relate_ray` twice though, or maybe you'll just call `relate_ray` on your end. If we are talking about mouse position, it's a single cast per frame, so any kind of conversion to/from a parametric form is irrelevant for the performance.

A `Bound` was designed like something that encloses a 3D volume, simple as that. The `relate_bound` I proposed would work on the `Self` type only. Is it any clearer now?

**Comment by kvark** [comment]
@bjz Since you are back and hacking in full sail already, perhaps you could comment here to update your position towards the subject? People are still hell of being confused.

**Comment by bjz** [comment]
Sorry! Good thought. I since being [kicked up the bottom](https://users.rust-lang.org/t/my-gamedever-wishlist-for-rust/2859) by @tomaka, I have decided to get back to updating cgmath. I tried nalgebra for a time, and found it hard to use, so I'm going to really try to polish cgmath with a view for improving ergonomics for gamedev use. So closing this now.

**Comment by kvark** [comment]
\o/ you made my day, @bjz ;)

Regards,
Dzmitry
